#!/usr/bin/env python3
"""Run repeatable IDA or GDB analysis scripts for an existing /re session.

This helper intentionally does not invent a command-line injection mechanism for
x64dbg because its documented CLI focuses on launching/attaching; x64dbg scripts
can be generated by the agent and loaded inside the debugger UI.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


def find_on_path(names: list[str]) -> str | None:
    for name in names:
        value = shutil.which(name)
        if value:
            return value
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tool", required=True, choices=["ida", "gdb", "gdp"])
    parser.add_argument("--target", help="target executable/file")
    parser.add_argument("--pid", type=int)
    parser.add_argument("--script", required=True, help="IDA Python script or GDB command file")
    parser.add_argument("--debugger", help="explicit debugger executable")
    parser.add_argument("--timeout", type=int, default=120)
    args = parser.parse_args()

    if args.tool == "gdp":
        args.tool = "gdb"

    script = Path(args.script).expanduser().resolve()
    if not script.is_file():
        print(f"ERROR: analysis script does not exist: {script}", file=sys.stderr)
        return 2

    if args.tool == "ida":
        if args.pid is not None:
            print("ERROR: scripted IDA batch mode requires a file/database target. Use IDA's debugger attach flow for a live PID.", file=sys.stderr)
            return 3
        if not args.target:
            print("ERROR: --target is required for IDA batch analysis.", file=sys.stderr)
            return 2
        target = Path(args.target).expanduser().resolve()
        if not target.is_file():
            print(f"ERROR: target does not exist: {target}", file=sys.stderr)
            return 2
        debugger = args.debugger
        if not debugger:
            env = os.environ.get("HCLI_CURRENT_IDA_INSTALL_DIR") or os.environ.get("IDADIR") or os.environ.get("IDA_PATH")
            if env:
                base = Path(env)
                if base.is_file():
                    debugger = str(base)
                else:
                    debugger = str(base / ("ida64.exe" if os.name == "nt" else "ida64"))
        if not debugger:
            debugger = find_on_path(["ida64.exe", "ida64", "ida.exe", "ida"])
        if not debugger:
            print("ERROR: IDA was not found. Set IDADIR/HCLI_CURRENT_IDA_INSTALL_DIR or pass --debugger.", file=sys.stderr)
            return 4
        cmd = [debugger, "-A", f"-S{script}", str(target)]
    else:
        debugger = args.debugger or os.environ.get("GDB_PATH") or os.environ.get("GDB") or find_on_path(["gdb.exe", "gdb"])
        if not debugger:
            print("ERROR: GDB was not found. Pass --debugger or put gdb on PATH.", file=sys.stderr)
            return 4
        if args.pid is not None:
            cmd = [debugger, "-q", "-nx", "-batch", "-x", str(script), "-p", str(args.pid)]
        elif args.target:
            target = Path(args.target).expanduser().resolve()
            if not target.is_file():
                print(f"ERROR: target does not exist: {target}", file=sys.stderr)
                return 2
            cmd = [debugger, "-q", "-nx", "-batch", "-x", str(script), str(target)]
        else:
            print("ERROR: --target or --pid is required for GDB.", file=sys.stderr)
            return 2

    try:
        completed = subprocess.run(cmd, capture_output=True, text=True, timeout=args.timeout, check=False)
    except subprocess.TimeoutExpired:
        print(f"ERROR: analysis command timed out after {args.timeout}s", file=sys.stderr)
        return 5
    except OSError as exc:
        print(f"ERROR: failed to start analysis tool: {exc}", file=sys.stderr)
        return 6

    print(completed.stdout, end="")
    if completed.stderr:
        print(completed.stderr, file=sys.stderr, end="")
    if completed.returncode != 0:
        print(f"ERROR: analysis tool exited with code {completed.returncode}", file=sys.stderr)
        return completed.returncode if completed.returncode > 0 else 7
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
